### PR TITLE
Added Effects in styling of FAQ Section ! #466 

### PR DESCRIPTION
**Pull request by Anmolreshi**
Hi ! 
I was assigned this issue #466  by @ravikr126  .
I have implemented the Required Changes in FAQ Section of Website Fronted . I have added hovering effects and with styling effect on box when its opened up ! Kindly review it and merge if found good !

### CODE REVIEW

**Comment by Anmolreshi** [comment]
@ravikr126 @harikesh409  Kindly Review It

**Review by harikesh409 — COMMENTED** [review]
The transition with that blue colour is looking odd.

**Comment by Anmolreshi** [comment]
@harikesh409  Well I can Change the Color but I took that variant because it basic color of your website so if anything different would look odd !  Anyways do you want me to change color only ?

**Review by ravikr126 — APPROVED** [review]

**Comment by Anmolreshi** [comment]
@harikesh409  Kindly help in merging this if this is conflict free !

**Comment by harikesh409** [comment]
> @harikesh409 Well I can Change the Color but I took that variant because it basic color of your website so if anything different would look odd ! Anyways do you want me to change color only ?

Yes I understand it is the base color of the theme itself but just seeing that color with white text felt odd anyways I will be merging it if needed we can change the color under a different issue.

**Pull request merged**
