### PR TITLE
Fixed margin and alignment bug in Suggested Books and Team section

### PR DESCRIPTION
**Pull request by ishitakapoor26**
Description
Resolved issue below are resolved issue images
Capture6
Capture7

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
    - After :
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Fixes: #537

### CODE REVIEW

**Comment by ishitakapoor26** [comment]
commit cd201d6
issue #537

**Comment by ishitakapoor26** [comment]
Pls review my pr @harikesh409 @anubhavitis @chaitanyashimpi @parthpandyappp

**Review by harikesh409 — CHANGES_REQUESTED** [review]
Remove the contact section changes.

**Comment by harikesh409** [comment]
Moved to #541

**Pull request closed without merging**
