### PR TITLE
Adding Learn more about Data Structures Section 

### LINKED ISSUE #109: [GSSOC'21] Learn more about Data Structures Section
Hi ! I am Malavika  , participating in  GSSOC'21 .
I would like to add a learn more about  Data structures section, where I would put the various data structures as cards with a learn more button . 
So Kindly please assign me this task.
Something like this .
Screenshot 2021-03-11 134405

### PR DESCRIPTION
**Pull request by malavikarajeshvikraman**
Hi  ,
I have added the Data Structure Section  ( fix #109 )!
[Screenshot 2021-03-11 134405](https://user-images.githubusercontent.com/42905287/111063911-2a73cf80-84d7-11eb-845c-a9d36b64d018.jpg)
Please do check and merge .

### CODE REVIEW

**Comment by Shruti3004** [comment]
great work @malavikarajeshvikraman

**Comment by Shruti3004** [comment]
Screenshot from 2021-03-15 20-32-41
@malavikarajeshvikraman great work but please make the following changes:

- Make the card sizes equal
- Add boder bottom to the complete section
- give the dark green (the shade which matches to the site) background to the bottom of the card where text is written

**Comment by malavikarajeshvikraman** [comment]
Okay So I will make a new pull request soon and fix it @Shruti3004 .

**Comment by Shruti3004** [comment]
@malavikarajeshvikraman great go ahead!

**Comment by malavikarajeshvikraman** [comment]
@Shruti3004  Please check PR #172

**Pull request merged**
