### PR TITLE
added features section

### LINKED ISSUE #229: Adding a features Section below About Us section.
## **Is your feature request related to a problem? Please describe.**

This is not a major problem but it could improve the User experience. One of the main aspect of the website is that it provides a vast amount of problems to practice on and as well as a roadmap. 
However both of these are present not being highlighted as they are only are situated in the footer and the "More" section in the navbar instead.

## **Describe the solution you'd like**

Addition of a small section below the "About Us" in homepage would help to put more emphasis and the user would be able to navigate much faster. It would contain a brief description of the features along with links to respective pages.

### PR DESCRIPTION
**Pull request by cryptofox17**
# Description
Added a Features Section below "About Us" Section. Used bootstrap classes to ensure it is responsive and followed the color scheme of the website.
 
Fixes #229 

## List any dependencies that are required for this change 
NA

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Ran on local server

## UI /UX changes
   - Before :
      
Screenshot (105)

  - After :
    
Screenshot (103)
Screenshot (104)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by harikesh409 — COMMENTED** [review]
Just thinking if it looks good if we have this section linked to the navbar.
What do you say @ravikr126

**Comment by harikesh409** [comment]
@cryptofox17 resolve merge conflicts

**Comment by cryptofox17** [comment]
@harikesh409 done resolving the conflicts

**Comment by ravikr126** [comment]
> Just thinking if it looks good if we have this section linked to the navbar.
> What do you say @ravikr126

yes, you think right .already home page is full of many things.if it possible she can create a new page where this thing are available

**Pull request closed without merging**
