### PR TITLE
navbar improved

### PR DESCRIPTION
**Pull request by bajajanjana**
# Description
Improved the navbar. Added an interesting bouncing effect in the navbar.

Please include a summary of the change and which issue is fixed.

Improved navbar by adding the following features.
•Bouncing effect - On scrolling, the navbar bounces upside and disappears for a while and then visible again.
• Added hr tag in menu list after each <a> tag.
• Hovering effect in hr tag.
Fixes (issue) #287 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have tested these changes by applying them to my local machine.
## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
   - 

https://user-images.githubusercontent.com/59495227/112950356-d49a5b00-9157-11eb-80c0-53ab2583ccb2.mp4

    - After :
    - 

https://user-images.githubusercontent.com/59495227/112951245-c39e1980-9158-11eb-8ccc-782b2fee8579.mp4

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bajajanjana** [comment]
@Shruti3004 @harikesh409 @ravikr126 please review these changes regarding navbar.

**Comment by harikesh409** [comment]
@bajajanjana resolve the conflicts.

**Review by ravikr126 — APPROVED** [review]

**Comment by ravikr126** [comment]
everything is good but resolve the conflicts @bajajanjana

**Comment by bajajanjana** [comment]
I'll resolve this conflict soom

**Comment by bajajanjana** [comment]
@harikesh409 @ravikr126 I have made a new PR #318  regarding the same issue #287 after solving the conflicts.
Please review the new PR #318 in place of this.

**Comment by harikesh409** [comment]
moved to #318

**Pull request closed without merging**
