### PR TITLE
Contact Form

### LINKED ISSUE #51: Add contact us form in the contact section.
I want to make the contact us section better by adding a form. Please assign me this issue.

### PR DESCRIPTION
**Pull request by padmajabhol**
pulled all the new codes and made the changes as requested.

# Description

Added a contact form to index.html and team.html

Please include a summary of the change and which issue is fixed.
Fixes #51 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
    - After :
Screenshot (89)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ravikr126 — CHANGES_REQUESTED** [review]
make a more compact contact form.it will take more space

**Comment by padmajabhol** [comment]
> make a more compact contact form.it will take more space

well, I did that earlier in my very first PR and was asked to change it, can you be a little more exact about how it should actually be?

**Comment by harshb02** [comment]
Can I also help in this issue @harikesh409

**Comment by harikesh409** [comment]
> Can I also help in this issue @harikesh409

It is upto @padmajabhol

**Comment by harikesh409** [comment]
Moved to #460

**Pull request closed without merging**
