### PR TITLE
Dark Theme Implementation

### LINKED ISSUE #32: Implementing Dark theme for the site

### PR DESCRIPTION
**Pull request by saaiswetha**
Closes #32

### CODE REVIEW

**Comment by saaiswetha** [comment]
@Shruti3004 do review my pr for merging and let me know in case of any changes.

**Comment by saaiswetha** [comment]
@Shruti3004 could u check out my PR?

**Comment by harikesh409** [comment]
Resolve the merge conflicts.
image

In the dark mode the about us section is merged with the contact section change those colors also.

**Comment by harikesh409** [comment]
No need of any dark theme for the site.
#376

**Pull request closed without merging**
