### PR TITLE
Preloader-added

### PR DESCRIPTION
**Pull request by Ankita297**
image

### CODE REVIEW

**Comment by Ankita297** [comment]
Preloader added to home page

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/109423092-31dda800-7a04-11eb-8913-ed9b6063beba.mp4

**Comment by Ankita297** [comment]
#29

**Comment by Ankita297** [comment]
Can you please add the GSSoc label ?

**Comment by abstrxtInfinity** [comment]
It will look a bit better if you could just hide the overflow on the pre-loader screen, so as the scroll bar is not visible.

**Pull request merged**
