### PR TITLE
Added Online Compiler

### LINKED ISSUE #218: Adding online compiler
## **Is your feature request related to a problem? Please describe.**

- code's link can be shared so we can get advice to make appropriate changes .

## **Describe the solution you'd like**

- online compiler for various languages like Java, C++, Python, etc.
- a simple UI in order to store all your codes written in various languages easily at one place.
- You can share the codes' links that you write with your friends without being worried about them making any changes.
- stores all your code details on your device, which means every code that you write will only be editable on the device where you write your code.

### PR DESCRIPTION
**Pull request by bitaashna**
# Description
Online compilerfor various languages C,C++,java has been added with a simple UI with a feature of light and dark mode
Fixes #218 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## UI /UX changes
  
Screenshot from 2021-03-28 14-07-00
Screenshot from 2021-03-28 14-06-51
Screenshot from 2021-03-28 14-06-48
Screenshot from 2021-03-28 14-00-53
Screenshot from 2021-03-28 14-00-49
Screenshot from 2021-03-28 14-00-08
Screenshot from 2021-03-28 14-00-04
Screenshot from 2021-03-28 13-59-55

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bitaashna** [comment]
@harikesh409 @rudrakshi99 @todi-2000 Please review it!

**Comment by ravikr126** [comment]
If you can change UI more stylish then make it .Make UI of compiler more user-friendly

**Comment by harikesh409** [comment]
> @harikesh409 @rudrakshi99 @todi-2000 Please review it!
> It's my first PR in this project :)

The functionality looks nice but the UI doesn't sync up with the existing site, you can use bootstrap and use the existing `styles.css`  so that the all pages in the site look similar. If you think you need help you can ask other members also you people can work combined.

**Required Changes:**
- [ ] Change layout by keeping the editor on the left and input and output on the right. You can keep language dropdown and run button on the same line.
- [ ] Use existing color scheme and bootstrap classes to make it responsive.
- [ ] As soon as the language changes the editor should either be cleared or re written the base code with the selected language.
- [ ] The textareas for code editor, input, and output shouldn't allow resizing.

**Review by harikesh409 — CHANGES_REQUESTED** [review]
Instead of creating a whole new folder use the existing folders only.
Place the html file in the root folder with `compiler.html` as name or something meaningful and move the styles and scripts to the respective folders with meaningful names.

**Comment by bitaashna** [comment]
> > @harikesh409 @rudrakshi99 @todi-2000 Please review it!
> > It's my first PR in this project :)
> 
> The functionality looks nice but the UI doesn't sync up with the existing site, you can use bootstrap and use the existing `styles.css` so that the all pages in the site look similar. If you think you need help you can ask other members also you people can work combined.
> 
> **Required Changes:**
> 
> * [ ]  Change layout by keeping the editor on the left and input and output on the right. You can keep language dropdown and run button on the same line.
> * [ ]  Use existing color scheme and bootstrap classes to make it responsive.
> * [ ]  As soon as the language changes the editor should either be cleared or re written the base code with the selected language.
> * [ ]  The textareas for code editor, input, and output shouldn't allow resizing.

Sure! I will do the changes

**Comment by harikesh409** [comment]
@bitaashna what is the progress?

**Comment by bitaashna** [comment]
> @bitaashna what is the progress?

Hi @harikesh409 ! I am having end sems so its difficult for me to do this.Can you please assign the changes required to someone else,it would be better. :)

**Comment by harikesh409** [comment]
> > @bitaashna what is the progress?
> 
> Hi @harikesh409 ! I am having end sems so its difficult for me to do this.Can you please assign the changes required to someone else,it would be better. :)

Okay

**Comment by amangupta37** [comment]
I want to work on this issue  @harikesh409 I think I have to work on the UI part as he has already embedded the compiler ??

**Comment by harikesh409** [comment]
> I want to work on this issue @harikesh409 I think I have to work on the UI part as he has already embedded the compiler ??

Yes see the comments.

**Comment by amangupta37** [comment]
> > @harikesh409 @rudrakshi99 @todi-2000 Please review it!
> > It's my first PR in this project :)
> 
> The functionality looks nice but the UI doesn't sync up with the existing site, you can use bootstrap and use the existing `styles.css` so that the all pages in the site look similar. If you think you need help you can ask other members also you people can work combined.
> 
> **Required Changes:**
> 
> * [ ]  Change layout by keeping the editor on the left and input and output on the right. You can keep language dropdown and run button on the same line.
> * [ ]  Use existing color scheme and bootstrap classes to make it responsive.
> * [ ]  As soon as the language changes the editor should either be cleared or re written the base code with the selected language.
> * [ ]  The textareas for code editor, input, and output shouldn't allow resizing.

ok then i will work as per your requirements

**Comment by harikesh409** [comment]
@amangupta37 What is the progress?

**Comment by amangupta37** [comment]
> > I want to work on this issue @harikesh409 I think I have to work on the UI part as he has already embedded the compiler ??
> 
> Yes see the comments.
due to my exams, progress was slow I need some time soon I will update u with the progress

**Comment by harikesh409** [comment]
> > > I want to work on this issue @harikesh409 I think I have to work on the UI part as he has already embedded the compiler ??
> > 
> > 
> > Yes see the comments.
> > due to my exams, progress was slow I need some time soon I will update u with the progress

It's been 19 days since we assigned you the issue how much more time do you need?

**Comment by amangupta37** [comment]
> > > > I want to work on this issue @harikesh409 I think I have to work on the UI part as he has already embedded the compiler ??
> > > 
> > > 
> > > Yes see the comments.
> > > due to my exams, progress was slow I need some time soon I will update u with the progress
> 
> It's been 19 days since we assigned you the issue how much more time do you need?

I really apologize for that Actually for past day's situation was really bad for me as our campus has Corona outburst and we as a student suffered a lot due to that and now finally we reached our home and stuck with exams….. If u can tell ur the deadline I will try to finish this task up to that date or if anyone else wants to work on this issue u can assign it to them.

**Comment by harikesh409** [comment]
> > > > > I want to work on this issue @harikesh409 I think I have to work on the UI part as he has already embedded the compiler ??
> > > > 
> > > > 
> > > > Yes see the comments.
> > > > due to my exams, progress was slow I need some time soon I will update u with the progress
> > 
> > 
> > It's been 19 days since we assigned you the issue how much more time do you need?
> 
> I really apologize for that Actually for past day's situation was really bad for me as our campus has Corona outburst and we as a student suffered a lot due to that and now finally we reached our home and stuck with exams….. If u can tell ur the deadline I will try to finish this task up to that date or if anyone else wants to work on this issue u can assign it to them.

Okay take care of your health but we can't give more than a week if you cannot show us any progress by then, we will assign it to someone else who is interested.

**Pull request closed without merging**
