### PR TITLE
added online compiler

### LINKED ISSUE #218: Adding online compiler
## **Is your feature request related to a problem? Please describe.**

- code's link can be shared so we can get advice to make appropriate changes .

## **Describe the solution you'd like**

- online compiler for various languages like Java, C++, Python, etc.
- a simple UI in order to store all your codes written in various languages easily at one place.
- You can share the codes' links that you write with your friends without being worried about them making any changes.
- stores all your code details on your device, which means every code that you write will only be editable on the device where you write your code.

### PR DESCRIPTION
**Pull request by subhangi2731**
# Description
Here code's link can be shared so we can get advice to make appropriate changes . This is online compiler for various languages like Java, C++, Python, etc. A simple UI in order to store all your codes written in various languages easily at one place. You can share the codes' links that you write with your friends without being worried about them making any changes.
stores all your code details on your device, which means every code that you write will only be editable on the device where you write your code.

Please include a summary of the change and which issue is fixed.
Fixes #218 

## List any dependencies that are required for this change 
I have added lib by extracting and compressing all the files and storing it in js/ and ide.html in parent folder and ide_style.css in css/

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
    - After :
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by subhangi2731** [comment]
@harikesh409 @ravikr126 please review and merge my pr

**Comment by subhangi2731** [comment]
Screenshot from 2021-05-23 23-17-25
Screenshot from 2021-05-23 23-18-54

**Comment by subhangi2731** [comment]
@harikesh409 @ravikr126 I did everything please merge my pr.

**Review by ravikr126 — COMMENTED** [review]
I think everything is good .Wait for @harikesh409 reviews

**Comment by subhangi2731** [comment]
@ravikr126 @harikesh409 please merge my pr

**Comment by subhangi2731** [comment]
@harikesh409 please review and merge my pr

**Comment by subhangi2731** [comment]
@harikesh409 @ravikr126 I request u please merge my pr

**Pull request merged**
