### PR TITLE
uppercase in team.html

### LINKED ISSUE #37: Suggestion: uppercase in team.html
Suggestion: uppercase in team.html
(testing issues and PR in GH)

### PR DESCRIPTION
**Pull request by mrunal512**
# Description

Please include a summary of the change and which issue is fixed.
Fixes #37

## List any dependencies that are required for this change 
none

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
on vs code

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
Screenshot 2021-05-22 at 10 26 52 PM
Screenshot 2021-05-22 at 10 26 37 PM
Screenshot 2021-05-22 at 10 26 29 PM

    - After :
 
Screenshot 2021-05-22 at 9 06 24 PM
Screenshot 2021-05-22 at 9 06 11 PM
Screenshot 2021-05-22 at 10 29 09 PM

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mrunal512** [comment]
I have added uppercase wherever needed and also fixed the grammatical errors

**Review by harikesh409 — CHANGES_REQUESTED** [review]
Why are the background.gif and video.mp4 replaced with .background.gif.icloud and .video.mp4.icloud?

**Review by mrunal512 — COMMENTED** [review]
please check the changes I have made in the team.html file

**Comment by harikesh409** [comment]
> please check the changes I have made in the team.html file

Still, 2 files were removed add them back and commit.

**Comment by mrunal512** [comment]
hello @harikesh409 
I have to tried to push the video folder back by committing the changes here as well as doing pull request once again.
but when I try to push the folder it gets converted to  .background.gif.icloud and .video.mp4.icloud automatically without any specific change from my side. 
hope that you could help me as this is my first contribution!

**Comment by harikesh409** [comment]
Moved to #512

**Pull request closed without merging**
